# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4
trigger: none

pr:
  branches:
    include:
    - main
    
pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  ResourceGroup: 'IKEA'
  AssignmentServiceName: 'app-ordercreate-assignmentservice-test'
  AppServiceName: 'app-pam-pull-request-test'
  AppServiceURL: 'https://app-pam-pull-request-test'
  URLSuffix: '.azurewebsites.net'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'sc-test-ikeaorderandcreate-nonprd'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az webapp deployment slot create --name $(AppServiceName) --resource-group $(ResourceGroup) --slot $(System.PullRequest.PullRequestNumber)'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'sc-test-ikeaorderandcreate-nonprd'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az webapp cors add -g $(ResourceGroup) -n $(AssignmentServiceName) --allowed-origins "$(AppServiceURL)-$(Build.SourceBranchName)$(URLSuffix)"'


- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'sc-test-ikeaorderandcreate-nonprd'
    appType: 'webApp'
    WebAppName: '$(AppServiceName)'
    deployToSlotOrASE: true
    ResourceGroupName: '$(ResourceGroup)'
    SlotName: '$(System.PullRequest.PullRequestNumber)'
    packageForLinux: '$(build.artifactStagingDirectory)/**/*.zip'