name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
       
    - name: Create Deployment Slot
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az rest --method GET --uri 'https://graph.microsoft.com/v1.0/applications/cbc0a9d5-1c7c-42b9-9589-7b6515a813c1' --query spa.redirectUris
